### ISSUE TITLE
Project name and url should be filled in automatically when Github URL is added

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/shipit#10]

**Comment by zachlatta** [comment]
Should any other fields be automatically populated?

**Comment by zachlatta** [comment]
Ah, good point. Can you add this to the issue's title?

**Comment by jonleung** [comment]
@zachlatta should we close this issue because we don't really use shipped right now?

/cc @MaxWofford

**Comment by zachlatta** [comment]
Closing because we're deprecating the repo.
