### ISSUE TITLE
Remove sensitive information from public

### ISSUE THREAD

**Issue by ifvictr** [hackclub/shipit#19]
Currently our API keys are publicly exposed. In the future, they should be stored via environment variables or configuration files in the backend.

**Comment by itsmingjie** [comment]
Refer to #12 

We have domain authentication and database permission rules set up in the back. Firebase API keys shouldn't be an issue.

**Comment by ifvictr** [comment]
No problems with Firebase (though I would prefer us giving as little away as possible), just Rebrandly.

**Comment by itsmingjie** [comment]
Thought about it overnight. My solution would be:

1. Make configuration files private - not including them in this repository
2. Remove domain `shipit.hackclub.com` from this repository
3. Deploy repository on Heroku still as a static site
4. Set API keys as config variables. 

This will take some time for me to change my static site into a node.js app, but this is probably the best solution I can think of. Tell me if this sounds right

**Comment by ifvictr** [comment]
Sounds about right. /cc @zachlatta

**Comment by ifvictr** [comment]
Sounds about right. @zachlatta What do you think about moving this to Heroku?

**Comment by zachlatta** [comment]
Which API keys are currently exposed? (Can you link to the files where they are too?)

Having Firebase public is fine. Would prefer to keep this as GitHub Pages if at all possible, because Heroku adds maintenance costs, but happy to switch over if it's actually needed.

**Comment by ifvictr** [comment]
Rebrandly is exposed:
https://github.com/hackclub/shipit/blob/master/asset/js/app.js#L101

**Comment by itsmingjie** [comment]
@zachlatta @ifvictr I don't think Rebrandly is a big issue either... Aside from possible security flaw of changing short link pointing. Another solution would be to just use Google Short Link and make shipit.tech work the same way as how `hack.af` is working, which cannot be modified even with the API key.

**Comment by ifvictr** [comment]
@mj66 I think we should move shortlinks to `hack.af` then. Current Rebrandly shortlinks should be kept.

**Comment by itsmingjie** [comment]
@ifvictr Great. Moving on to that then.
