### ISSUE TITLE
Anyone should be able to contribute

### ISSUE THREAD

**Issue by zachlatta** [hackclub/shipit#40]
Right now we have a dropdown of clubs that people must choose from to contribute. As brought up by @paked in hackedu/hackedu#119, i'd be great if anyone could create new clubs as well.

**Comment by paked** [comment]
Is there anything specifically that needs to be changed in order to make this happen? In my head all we have to do is change the dropdown to a textfield, but I don't know the codebase.

**Comment by jonleung** [comment]
@zachlatta should we close this issue because we don't really use shipped right now?

**Comment by zachlatta** [comment]
How to do this issue:

Basically do what @paked suggested. Have an option for an "Other" club and make it so they can type in the name of their school.

**Comment by zachlatta** [comment]
Closing because we're deprecating the repo.
