### ISSUE TITLE
Dropdown for github URL

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/shipit#5]
It would be streamline the process of submitting a project to the app if a list of the users repos were presented so they didn't have to have memorized the url or open a new tab to find it.

**Comment by zachlatta** [comment]
Moving work to here from #4.

**Comment by TheThirdOne** [comment]
Did we type this at the exact same time?

**Comment by zachlatta** [comment]
I believe we did. Maybe this is what destiny feels like.

**Comment by jonleung** [comment]
@zachlatta should we close this issue because we don't really use shipped right now?

/cc @MaxWofford

**Comment by MaxWofford** [comment]
Fine with this for the time being.

**Comment by MaxWofford** [comment]
My bad, didn't mean to close the issue

**Comment by zachlatta** [comment]
Closing because we're deprecating the repo.
