### ISSUE TITLE
Fix apostrophe escaping

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/shipit#51]
It looks like apostrophes are escaped in the yaml files shipit generates.

![screenshot_2016-04-17_13 39 16](https://cloud.githubusercontent.com/assets/5891442/14588841/ce722138-04a1-11e6-85b7-c59a2e16f31d.png)

**Comment by zachlatta** [comment]
Mmmm, good catch. Let's fix this.

**Comment by zachlatta** [comment]
Closing due to deprecation of repository.
